// apps/web/app/pages/settings/data.vue
<script setup lang="ts">
useSeoMeta({ title: 'データ管理設定' })
</script>

<template>
  <div class="space-y-6">
    <UCard>
      <template #header>
        <h2 class="text-lg font-semibold">
          データのエクスポート
        </h2>
        <p class="mt-2 text-sm text-muted">
          登録済みの収支データをCSVファイル（UTF-8・BOM付き）としてダウンロードできます。
        </p>
      </template>
      <div class="flex flex-col gap-3 sm:flex-row">
        <UButton
          to="/api/export/expenses"
          external
          download
          color="neutral"
          variant="outline"
          icon="i-lucide-download"
        >
          支出データ（CSV）
        </UButton>
        <UButton
          to="/api/export/incomes"
          external
          download
          color="neutral"
          variant="outline"
          icon="i-lucide-download"
        >
          収入データ（CSV）
        </UButton>
      </div>
    </UCard>
    <UCard>
      <template #header>
        <h2 class="text-lg font-semibold">
          フルバックアップ
        </h2>
        <p class="mt-2 text-sm text-muted">
          カテゴリや設定を含むすべてのデータをSQLiteデータベースとしてダウンロードできます。
        </p>
      </template>
      <UButton
        to="/api/backup"
        external
        download
        color="neutral"
        variant="outline"
        icon="i-lucide-download"
      >
        バックアップをダウンロード
      </UButton>
    </UCard>
    <UCard>
      <template #header>
        <h2 class="text-lg font-semibold">
          データのインポート
        </h2>
        <p class="mt-2 text-sm text-muted">
          CSVファイルを選択すると内容を確認してから登録できます。登録前にデータベースへの反映は行われません。
        </p>
      </template>
      <div class="flex flex-col gap-6">
        <div>
          <h3 class="mb-2 text-sm font-semibold">
            支出データ
          </h3>
          <SettingsCsvImportPanel kind="expense" />
        </div>
        <USeparator />
        <div>
          <h3 class="mb-2 text-sm font-semibold">
            収入データ
          </h3>
          <SettingsCsvImportPanel kind="income" />
        </div>
        <USeparator />
        <div>
          <h3 class="mb-2 text-sm font-semibold">
            固定費データ
          </h3>
          <SettingsCsvImportPanel kind="recurring-expense" />
        </div>
      </div>
    </UCard>
  </div>
</template>

// apps/web/src/routes/settings/data/+page.svelte
<script lang="ts">
  import ArrowLeftIcon from '@lucide/svelte/icons/arrow-left';
  import DownloadIcon from '@lucide/svelte/icons/download';
  import UploadIcon from '@lucide/svelte/icons/upload';
  import { Button } from '$lib/components/ui/button';
  import * as Card from '$lib/components/ui/card';
  import Header from '$lib/components/Header.svelte';
  import CsvImport from '$lib/features/settings/CsvImport.svelte';
</script>

<svelte:head>
  <title>データ管理 | Kakeibo</title>
  <meta name="description" content="収支データのインポート・エクスポート" />
</svelte:head>

<div class="min-h-screen bg-background">
  <Header />
  <main class="mx-auto flex max-w-5xl flex-col gap-6 px-5 py-8 lg:px-10 lg:py-12">
    <div>
      <Button variant="ghost" size="sm" href="/settings">
        <ArrowLeftIcon data-icon="inline-start" />設定に戻る
      </Button>
    </div>

    <div class="flex flex-col gap-2">
      <p class="text-xs font-semibold tracking-widest text-muted-foreground uppercase">Settings</p>
      <h1 class="font-serif text-3xl font-bold tracking-tight sm:text-4xl">データ管理</h1>
      <p class="text-muted-foreground">収支データのインポート・エクスポートができます。</p>
    </div>

    <Card.Root>
      <Card.Header>
        <Card.Title class="flex items-center gap-2">
          <DownloadIcon />データのエクスポート
        </Card.Title>
        <Card.Description>
          登録済みの収支データをCSVファイル（UTF-8・BOM付き）としてダウンロードできます。
        </Card.Description>
      </Card.Header>
      <Card.Content class="flex flex-col gap-3 sm:flex-row">
        <Button variant="outline" href="/api/export/expenses">
          <DownloadIcon data-icon="inline-start" />支出データ（CSV）
        </Button>
        <Button variant="outline" href="/api/export/incomes">
          <DownloadIcon data-icon="inline-start" />収入データ（CSV）
        </Button>
      </Card.Content>
    </Card.Root>

    <Card.Root>
      <Card.Header>
        <Card.Title class="flex items-center gap-2">
          <DownloadIcon />フルバックアップ
        </Card.Title>
        <Card.Description>
          カテゴリや設定を含むすべてのデータをSQLiteデータベースとしてダウンロードできます。
        </Card.Description>
      </Card.Header>
      <Card.Content>
        <Button variant="outline" href="/api/backup">
          <DownloadIcon data-icon="inline-start" />バックアップをダウンロード
        </Button>
      </Card.Content>
    </Card.Root>

    <Card.Root>
      <Card.Header>
        <Card.Title class="flex items-center gap-2">
          <UploadIcon />データのインポート
        </Card.Title>
        <Card.Description>
          ヘッダーは名前と順序を完全に一致させてください。日付はYYYY-MM-DD、金額は記号・桁区切り・小数なしの正の整数で指定します。カテゴリと支出の支払方法は必須です。メモは空欄にできますが、列は必要です。未登録のカテゴリや支払方法は自動的に追加されます。同じファイルを再度取り込むと重複して登録されるためご注意ください。
        </Card.Description>
      </Card.Header>
      <Card.Content class="flex flex-col gap-4 sm:flex-row sm:gap-8">
        <CsvImport kind="expense" />
        <CsvImport kind="income" />
      </Card.Content>
    </Card.Root>
  </main>
</div>
